---
title: "In-Class Ex04"
format: html
editor: visual
date: "February 8, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# In-Class Exercise 4

## Getting Start

------------------------------------------------------------------------

The code chunk below will be used load these R packages into RStudio environment.

```{r}
pacman::p_load(haven, SmartEDA, tidymodels,
               tidyverse)
```

## Data Import

------------------------------------------------------------------------

For the purpose of this In-Class Exercise, Exam_data.csv will be used.

In the code chunk below, read_csv () of reader packages is used to import Exam_data.csv into R and saved it into a tibble data.frame.

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

## Visualizing Distribution with Boxplot

------------------------------------------------------------------------

The boxplot below is plotted by using **ggplot**.

```{r}
ggplot(exam_data, 
       aes(x = ENGLISH,
           y = CLASS)) + 
  geom_boxplot()
```
