{
  "hash": "ce0f56e79403615781232f2624f702a5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 3 Part 1\"\nauthor: \"Lai Meihao\"\ndate: \"March 25, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1.Overview\n\n## 1.1 Project Brief\n\nTake home exercise 3 is a preliminary work of the group project - blue pulse. Water is essential to life, yet billions worldwide still lack access to safe drinking water and sanitation. Waterborne disease such as acute hepatitis A and diarrhea continue to pose series public health threats, particularly in regions with inadequate water access. SDG 6 aims to ensure universal access to water and sanitation The project aims to understand the 1) understand the distribution of water access and safety by region, 2) analyze the long-term effects of water access on health outcome.\n\nThe project team consists of three members and each member will take one of the main prototype modules as follows:\n\n-   Exploratory Data Analysis (initial & treemap)\n\n-   Panel Linear Model for observations over time for multiple entities (regions, countries)\n\n-   Confirmatory Data Analysis.\n\n## 1.2 Project Objectives\n\nThe project will using WDI from world bank and burden of disease from institute for health metrics and evaluation. The objective of this take-home exercise is to build a prototype - user interface design on Panel Linear Model.\n\n# 2. Initial Data Preparation\n\n## 2.1 Install and launch R packages\n\nThe project uses `p_load()` of pacman package to check if the R package are installed in the computer.\n\nThe following code chunk is used to install and launch the R packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, ggplot2, plm,ExPanDaR,lubridate, ggthemes, plotly,dplyr,purrr,forecast)\n```\n:::\n\n\n\n## 2.2 Import Data\n\nThe project examine the dataset from WDI from world bank and burden of disease from institute for health metrics and evaluation focusing on WHO region countries from 2000 to 2021.\\\nThe data have already have been initally processed and merged by member of the team - Xinyue.\n\nThe below code chunk use `read_csv()` to read the csv file into R as a data frame\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmerged_data <- read_csv(\"data/merged_data.csv\")\n```\n:::\n\n\n\n## **2.3 Overview of the data**\n\n### **Dataset Structure**\n\nThe below code chunk check the structure of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preview structure and types\nglimpse(merged_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,232\nColumns: 8\n$ Region        <chr> \"Region of the Americas\", \"Region of the Americas\", \"Reg…\n$ Year          <dbl> 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 20…\n$ TyphoidRate   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ DiarrheaRate  <dbl> 5.88, 5.88, 5.88, 5.88, 5.88, 5.88, 5.88, 5.88, 5.88, 5.…\n$ HepatitisRate <dbl> 0.38, 0.38, 0.38, 0.38, 0.38, 0.38, 0.38, 0.38, 0.38, 0.…\n$ UnsafeRisk    <dbl> 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.…\n$ Series.Name   <chr> \"Level of water stress: freshwater withdrawal as a propo…\n$ AvgValue      <dbl> 1.308801e+01, 8.252346e+00, 8.867545e+01, 7.710693e+01, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# View first few rows\nhead(merged_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  Region      Year TyphoidRate DiarrheaRate HepatitisRate UnsafeRisk Series.Name\n  <chr>      <dbl>       <dbl>        <dbl>         <dbl>      <dbl> <chr>      \n1 Region of…  2000           0         5.88          0.38          1 Level of w…\n2 Region of…  2000           0         5.88          0.38          1 People pra…\n3 Region of…  2000           0         5.88          0.38          1 People usi…\n4 Region of…  2000           0         5.88          0.38          1 People usi…\n5 Region of…  2000           0         5.88          0.38          1 People usi…\n6 Region of…  2000           0         5.88          0.38          1 People usi…\n# ℹ 1 more variable: AvgValue <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# View in spreadsheet-style window\nView(merged_data)\n```\n:::\n\n\n\n# 3.Data Processing\n\n## 3.1 Missing Data\n\nThe below code chunk of `is.na()` to check the missing values in the `merged_data` frame, and returns a logical matrix( or vector, depending on the data structure. `sum()` function calculate the sum of the elements of the logical matrix or vector.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(merged_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\nThe result of zero indicate that there no missing in the merge dataset.\n\n## 3.2 Duplicate Value\n\nThe `duplicated()` function checks for duplicate rows in the `merged_data` frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(merged_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\nThe result indicate that there is no duplicate in the `merged_data`.\n\n# 4.PLM: Linear Model for panel data\n\n## 4.1 Overview of plm\n\nA **Panel Linear Model (PLM)** is a statistical model used to analyze data that includes observations over time (time-series) and across different units (cross-sectional). This type of data, often called panel data or longitudinal data, involves multiple subjects (such as countries, individuals, or companies) observed over several time periods.\n\nFor this project, we are using data from the World Development Indicators (WDI) as WASH (Water, Sanitation, and Hygiene) indicators and data from the Institute for Health Metrics as health indicators. We will apply the PLM to estimate the coefficients of the WASH indicators for each health indicator. Subsequently, we will use time-series analysis to forecast trends for the health indicators, particularly disease rates, based on the coefficients obtained from the WASH indicators.\n\nTo apply PLM in our project, we will be using [`plm`](https://cran.r-project.org/web/packages/plm/plm.pdf) package in R.\n\n## 4.2 Creating Panel Data\n\nBefore proceed to the PLM analysis, we will first create panel data. We will be start by understanding `merged_data`.\\\nThe below code chunk use `names()` function to extract the names of the columns in the `merged_data`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(merged_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Region\"        \"Year\"          \"TyphoidRate\"   \"DiarrheaRate\" \n[5] \"HepatitisRate\" \"UnsafeRisk\"    \"Series.Name\"   \"AvgValue\"     \n```\n\n\n:::\n:::\n\n\n\nThe output shows the columns in the `merged_data`.\n\nThe below code chunk use the `summary()` function to provide a quick overview of each column in a dataframe.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(merged_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Region               Year       TyphoidRate       DiarrheaRate  \n Length:1232        Min.   :2000   Min.   :0.00000   Min.   : 2.72  \n Class :character   1st Qu.:2005   1st Qu.:0.00000   1st Qu.: 5.27  \n Mode  :character   Median :2010   Median :0.01500   Median : 8.80  \n                    Mean   :2010   Mean   :0.03614   Mean   :12.05  \n                    3rd Qu.:2016   3rd Qu.:0.04000   3rd Qu.:21.36  \n                    Max.   :2021   Max.   :0.22000   Max.   :22.74  \n HepatitisRate      UnsafeRisk     Series.Name           AvgValue        \n Min.   :0.2800   Min.   : 0.080   Length:1232        Min.   :        0  \n 1st Qu.:0.3700   1st Qu.: 0.290   Class :character   1st Qu.:       33  \n Median :0.4800   Median : 1.245   Mode  :character   Median :       71  \n Mean   :0.5292   Mean   : 3.470                      Mean   :  5899097  \n 3rd Qu.:0.6800   3rd Qu.: 6.607                      3rd Qu.:      104  \n Max.   :0.8300   Max.   :10.680                      Max.   :187658229  \n```\n\n\n:::\n:::\n\n\n\nThis summary provides key insights into the distribution and spread of values in each of the columns. The `AvgValue` column, for instance, has a wide range, with very large maximum values compared to the median and first quartile. Similarly, health indicators like `TyphoidRate`, `DiarrheaRate`, and `HepatitisRate` show varying levels of distribution, with some regions having very low rates and others experiencing high rates.\n\nThe below code chunk use `str()` function to display the structure of the merged_data. It provides a compact overview of the data type of each column, as well as the first few entries in each column.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(merged_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [1,232 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Region       : chr [1:1232] \"Region of the Americas\" \"Region of the Americas\" \"Region of the Americas\" \"Region of the Americas\" ...\n $ Year         : num [1:1232] 2000 2000 2000 2000 2000 ...\n $ TyphoidRate  : num [1:1232] 0 0 0 0 0 0 0 0 0 0 ...\n $ DiarrheaRate : num [1:1232] 5.88 5.88 5.88 5.88 5.88 5.88 5.88 5.88 5.88 5.81 ...\n $ HepatitisRate: num [1:1232] 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 ...\n $ UnsafeRisk   : num [1:1232] 1 1 1 1 1 1 1 1 1 0.94 ...\n $ Series.Name  : chr [1:1232] \"Level of water stress: freshwater withdrawal as a proportion of available freshwater resources\" \"People practicing open defecation (% of population)\" \"People using at least basic drinking water services (% of population)\" \"People using at least basic sanitation services (% of population)\" ...\n $ AvgValue     : num [1:1232] 13.09 8.25 88.68 77.11 61.49 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   Region = col_character(),\n  ..   Year = col_double(),\n  ..   TyphoidRate = col_double(),\n  ..   DiarrheaRate = col_double(),\n  ..   HepatitisRate = col_double(),\n  ..   UnsafeRisk = col_double(),\n  ..   Series.Name = col_character(),\n  ..   AvgValue = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\n\nThe dataset is a **spec_tbl_df** (which is a specific type of tibble in R) with **1232 rows and 8 columns**. The dataset includes 8 variables (columns), and it uses the `spec_tbl_df` class from the `tibble` package.\n\nThe below code chunk summaries the `merged_data` set by grouping it by `Region` and `Year`.\n\nThe result of this code is a new data frame, `merged_data_clean`, where:\n\n-   Each row corresponds to a unique combination of `Region` and `Year`.\n\n-   For each `Region` and `Year`, the mean values for `TyphoidRate`, `DiarrheaRate`, `HepatitisRate`, and `UnsafeRisk` are calculated, ignoring missing values.\n\nThe code chunk below use the `pivot_wider()` function from the `tidyverse` package to transform the `merged_data` dataset from long format to wide format. As the WASH indicator are store in the column `Series.Name`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwide_data <- merged_data %>%\n  pivot_wider(\n    id_cols = c(Region, Year, TyphoidRate, DiarrheaRate, HepatitisRate, UnsafeRisk),\n    names_from = Series.Name,\n    values_from = AvgValue\n  )\n```\n:::\n\n\n\nThe code chunk below creates a panel data frame using the `pdata.frame()` function from the `plm` package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npdata <- pdata.frame(wide_data, index = c(\"Region\", \"Year\"))\n```\n:::\n\n\n\nThe result of this code is that the `wide_data` data frame is now transformed into a **panel data frame**, stored in the variable `pdata`. This allows we to perform panel data analysis using the `plm` package.\n\n-   The `pdata` object will now be suitable for running panel regressions, such as fixed effects or random effects models, using functions like `plm()` from the `plm` package.\n\nThe below code chunk use `colnames()` function to return the column names of the `pdata` which is now a panel data after being converted by `pdata.frame()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(pdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Region\"                                                                                          \n [2] \"Year\"                                                                                            \n [3] \"TyphoidRate\"                                                                                     \n [4] \"DiarrheaRate\"                                                                                    \n [5] \"HepatitisRate\"                                                                                   \n [6] \"UnsafeRisk\"                                                                                      \n [7] \"Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources\"  \n [8] \"People.practicing.open.defecation....of.population.\"                                             \n [9] \"People.using.at.least.basic.drinking.water.services....of.population.\"                           \n[10] \"People.using.at.least.basic.sanitation.services....of.population.\"                               \n[11] \"People.using.safely.managed.drinking.water.services....of.population.\"                           \n[12] \"People.using.safely.managed.sanitation.services....of.population.\"                               \n[13] \"Population.density..people.per.sq..km.of.land.area.\"                                             \n[14] \"Population..total\"                                                                               \n[15] \"Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.\"\n[16] \"People.with.basic.handwashing.facilities.including.soap.and.water....of.population.\"             \n```\n\n\n:::\n:::\n\n\n\nThe `view()` function will open the `pdata` in a spreadsheet-like viewer in Rstudio.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nview(pdata)\n```\n:::\n\n\n\n## 4.3 PLM\n\n### 4.3.1 Initial run of the Model to confirm the variables\n\nWe will be use the `DiarrheaRate` as a sample to test the performance of our initially selected indicator in the `plm`.\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R.\n\nThe **Fixed Effects Model** estimates how changes in the predictor variables (e.g., sanitation services, population density, water stress) influence the **DiarrheaRate** within each `Region` across different years, controlling for unobserved time-invariant characteristics of each region (such as cultural or geographical factors).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  People.with.basic.handwashing.facilities.including.soap.and.water....of.population. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    People.with.basic.handwashing.facilities.including.soap.and.water....of.population. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 2, T = 22, N = 44\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-0.392560 -0.134377  0.014806  0.108757  0.427933 \n\nCoefficients:\n                                                                                                   Estimate\nPeople.practicing.open.defecation....of.population.                                              -5.4100263\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -5.3457243\nPeople.using.at.least.basic.sanitation.services....of.population.                                -1.7417929\nPopulation.density..people.per.sq..km.of.land.area.                                              -0.0422531\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. -0.0076615\nPeople.with.basic.handwashing.facilities.including.soap.and.water....of.population.               1.0010965\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -0.4339040\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.4378541\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.3559744\n                                                                                                 Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.8536717\nPeople.using.at.least.basic.drinking.water.services....of.population.                             1.6590995\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.6523631\nPopulation.density..people.per.sq..km.of.land.area.                                               0.0204327\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0157129\nPeople.with.basic.handwashing.facilities.including.soap.and.water....of.population.               0.2128349\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.1650806\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.2499438\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.6116180\n                                                                                                 t-value\nPeople.practicing.open.defecation....of.population.                                              -6.3374\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -3.2221\nPeople.using.at.least.basic.sanitation.services....of.population.                                -2.6700\nPopulation.density..people.per.sq..km.of.land.area.                                              -2.0679\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. -0.4876\nPeople.with.basic.handwashing.facilities.including.soap.and.water....of.population.               4.7036\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -2.6284\nPeople.using.safely.managed.drinking.water.services....of.population.                             1.7518\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.5820\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              3.587e-07\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.002861\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.011679\nPopulation.density..people.per.sq..km.of.land.area.                                               0.046561\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.629061\nPeople.with.basic.handwashing.facilities.including.soap.and.water....of.population.              4.406e-05\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.012920\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.089096\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.564508\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ** \nPeople.using.at.least.basic.sanitation.services....of.population.                                *  \nPopulation.density..people.per.sq..km.of.land.area.                                              *  \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.    \nPeople.with.basic.handwashing.facilities.including.soap.and.water....of.population.              ***\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   *  \nPeople.using.safely.managed.drinking.water.services....of.population.                            .  \nPeople.using.safely.managed.sanitation.services....of.population.                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    62.639\nResidual Sum of Squares: 1.4762\nR-Squared:      0.97643\nAdj. R-Squared: 0.96929\nF-statistic: 151.923 on 9 and 33 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nModel Details base on the result:\n\n-   Balanced Panel: The dataset used for the model has 2 cross-sectional units (regions) and 22 time periods, resulting in a total of 44 observations.\n\n-   Model: The model used is the Within Model (Fixed Effects), which controls for time-invariant characteristics of each region.\n\nHowever, we had 6 regions but the result was only 2 regions. It is likely there are missing values in the key variables.\n\nThe below code chunk check for the missing data in the `pdata`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(pdata))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                                          Region \n                                                                                               0 \n                                                                                            Year \n                                                                                               0 \n                                                                                     TyphoidRate \n                                                                                               0 \n                                                                                    DiarrheaRate \n                                                                                               0 \n                                                                                   HepatitisRate \n                                                                                               0 \n                                                                                      UnsafeRisk \n                                                                                               0 \n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources \n                                                                                               0 \n                                             People.practicing.open.defecation....of.population. \n                                                                                               0 \n                           People.using.at.least.basic.drinking.water.services....of.population. \n                                                                                               0 \n                               People.using.at.least.basic.sanitation.services....of.population. \n                                                                                               0 \n                           People.using.safely.managed.drinking.water.services....of.population. \n                                                                                               0 \n                               People.using.safely.managed.sanitation.services....of.population. \n                                                                                               0 \n                                             Population.density..people.per.sq..km.of.land.area. \n                                                                                               0 \n                                                                               Population..total \n                                                                                               0 \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. \n                                                                                               0 \n             People.with.basic.handwashing.facilities.including.soap.and.water....of.population. \n                                                                                              88 \n```\n\n\n:::\n:::\n\n\n\nThe result shows there are 88 missing value in the `People.with.basic.handwashing.facilities.including.soap.and.water....of.population.`\n\nIt was decide to remove the `People.with.basic.handwashing.facilities.including.soap.and.water....of.population.` from the model to if there is any improvement.\n\n### 4.3.2 Model run after remove `People.with.basic.handwashing.facilities.including.soap.and.water....of.population.`\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.021289 -0.248422 -0.060002  0.257269  0.961836 \n\nCoefficients:\n                                                                                                   Estimate\nPeople.practicing.open.defecation....of.population.                                              -0.6755407\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -1.0144098\nPeople.using.at.least.basic.sanitation.services....of.population.                                -0.1706479\nPopulation.density..people.per.sq..km.of.land.area.                                               0.0014148\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0029523\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0110199\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.2855646\nPeople.using.safely.managed.sanitation.services....of.population.                                -0.1302516\n                                                                                                 Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.1085486\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.1014805\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.0915876\nPopulation.density..people.per.sq..km.of.land.area.                                               0.0052560\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0011407\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0034595\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.1001031\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.1234424\n                                                                                                 t-value\nPeople.practicing.open.defecation....of.population.                                              -6.2234\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -9.9961\nPeople.using.at.least.basic.sanitation.services....of.population.                                -1.8632\nPopulation.density..people.per.sq..km.of.land.area.                                               0.2692\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  2.5882\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    3.1854\nPeople.using.safely.managed.drinking.water.services....of.population.                             2.8527\nPeople.using.safely.managed.sanitation.services....of.population.                                -1.0552\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              7.677e-09\nPeople.using.at.least.basic.drinking.water.services....of.population.                            < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.064917\nPopulation.density..people.per.sq..km.of.land.area.                                               0.788259\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.010860\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.001849\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.005120\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.293507\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                .  \nPopulation.density..people.per.sq..km.of.land.area.                                                 \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. *  \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ** \nPeople.using.safely.managed.drinking.water.services....of.population.                            ** \nPeople.using.safely.managed.sanitation.services....of.population.                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    146.4\nResidual Sum of Squares: 21.365\nR-Squared:      0.85406\nAdj. R-Squared: 0.83798\nF-statistic: 86.3196 on 8 and 118 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nModel Overview base on the result:\n\n-   Balanced Panel: The dataset consists of 6 regions (cross-sectional units) and 22 time periods, with a total of 132 observations.\n\n-   Model Type: Fixed Effects Model (within), which controls for time-invariant characteristics of each region.\n\nModel Summary:\n\n-   R-Squared: 0.85406, meaning the model explains 85.4% of the variance in DiarrheaRate.\n\n-   Adj. R-Squared: 0.83798, a good adjustment for the number of predictors.\n\n-   F-statistic: 86.3196 (p-value \\< 2.22e-16), showing that the model is highly significant.\n\nThe fixed effects model indicates that factors like open defecation, basic drinking water services, water stress, and water productivity are significantly related to DiarrheaRate, while factors like population density and safely managed sanitation services are not significant in this context. The high R-squared value suggests that the model is a good fit for the data.\\\n\nIt was decide to continue to test for removing the non-significant variables. By removing `Population.density` and `People.using.safely.managed.sanitation.services` to simplify the model.\n\n### 4.3.3 Test run removing variables `Population.density` and `People.using.safely.managed.sanitation.services`\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n  People.using.safely.managed.drinking.water.services....of.population. ,  \n  \n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.168524 -0.240715 -0.049543  0.265830  0.931916 \n\nCoefficients:\n                                                                                                   Estimate\nPeople.practicing.open.defecation....of.population.                                              -0.7173815\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -0.9650715\nPeople.using.at.least.basic.sanitation.services....of.population.                                -0.2551938\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0022381\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0124606\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.1885433\n                                                                                                 Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.1047691\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.0921281\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.0634282\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0010377\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0026884\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.0639472\n                                                                                                  t-value\nPeople.practicing.open.defecation....of.population.                                               -6.8473\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -10.4753\nPeople.using.at.least.basic.sanitation.services....of.population.                                 -4.0234\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.   2.1568\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources     4.6350\nPeople.using.safely.managed.drinking.water.services....of.population.                              2.9484\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              3.422e-10\nPeople.using.at.least.basic.drinking.water.services....of.population.                            < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                                0.0001008\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. 0.0330192\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   9.149e-06\nPeople.using.safely.managed.drinking.water.services....of.population.                            0.0038398\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                ***\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. *  \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ***\nPeople.using.safely.managed.drinking.water.services....of.population.                            ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    146.4\nResidual Sum of Squares: 21.782\nR-Squared:      0.85121\nAdj. R-Squared: 0.83758\nF-statistic: 114.421 on 6 and 120 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nModel Overview:\n\n-   Balanced Panel: The dataset consists of 6 regions (cross-sectional units) and 22 time periods, with a total of 132 observations.\n\n-   Model Type: The model used is the Fixed Effects Model (within), which controls for time-invariant characteristics of each region.\n\nModel Fit:\n\n-   R-Squared: The model explains 85.12% of the variance in DiarrheaRate, indicating a strong fit.\n\n-   Adjusted R-Squared: 83.76%, showing that the model explains most of the variance even after accounting for the number of predictors.\n\n-   F-statistic: 114.42 on 6 and 120 degrees of freedom, with a p-value \\< 2.22e-16, confirming that the model is statistically significant.\n\nThe fixed effects model indicates that open defecation, drinking water access, and sanitation services are the most significant factors influencing DiarrheaRate across regions. Other factors like water productivity and water stress also have significant effects. The high R-squared value suggests that the model explains most of the variation in diarrhea rates, and the predictors are statistically significant.\n\n### 4.3.4 Model Comparsion\n\nIt was then decide to compare the model to decide which will be apply in the further analysis.\n\nThe below code chunk fits a fixed Fixed Effects Model using the `plm` function, with the DiarrheaRate as the dependent variables and all the predictors after removing `People.using.safely.managed.sanitation.services`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original Model (all predictors)\nmodel_full <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +\n  People.using.safely.managed.drinking.water.services....of.population., \n  data = pdata, model = \"within\")\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.168524 -0.240715 -0.049543  0.265830  0.931916 \n\nCoefficients:\n                                                                                                   Estimate\nPeople.practicing.open.defecation....of.population.                                              -0.7173815\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -0.9650715\nPeople.using.at.least.basic.sanitation.services....of.population.                                -0.2551938\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0022381\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0124606\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.1885433\n                                                                                                 Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.1047691\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.0921281\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.0634282\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0010377\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0026884\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.0639472\n                                                                                                  t-value\nPeople.practicing.open.defecation....of.population.                                               -6.8473\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -10.4753\nPeople.using.at.least.basic.sanitation.services....of.population.                                 -4.0234\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.   2.1568\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources     4.6350\nPeople.using.safely.managed.drinking.water.services....of.population.                              2.9484\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              3.422e-10\nPeople.using.at.least.basic.drinking.water.services....of.population.                            < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                                0.0001008\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. 0.0330192\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   9.149e-06\nPeople.using.safely.managed.drinking.water.services....of.population.                            0.0038398\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                ***\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. *  \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ***\nPeople.using.safely.managed.drinking.water.services....of.population.                            ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    146.4\nResidual Sum of Squares: 21.782\nR-Squared:      0.85121\nAdj. R-Squared: 0.83758\nF-statistic: 114.421 on 6 and 120 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk fits a fixed Fixed Effects Model using the `plm` function, with the DiarrheaRate as the dependent variables and remove the non-significant variables including `Population.density` and `People.using.safely.managed.sanitation.services` .\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reduced Model (without non-significant predictors)\nmodel_reduced <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +\n  People.using.safely.managed.drinking.water.services....of.population., \n  data = pdata, model = \"within\")\nsummary(model_reduced)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.095461 -0.254637 -0.065977  0.290760  0.940495 \n\nCoefficients:\n                                                                                                 Estimate\nPeople.practicing.open.defecation....of.population.                                            -0.7052695\nPeople.using.at.least.basic.drinking.water.services....of.population.                          -0.9602699\nPeople.using.at.least.basic.sanitation.services....of.population.                              -0.2408893\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources  0.0121373\nPeople.using.safely.managed.drinking.water.services....of.population.                           0.1882391\n                                                                                               Std. Error\nPeople.practicing.open.defecation....of.population.                                             0.1061853\nPeople.using.at.least.basic.drinking.water.services....of.population.                           0.0934806\nPeople.using.at.least.basic.sanitation.services....of.population.                               0.0640252\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources  0.0027244\nPeople.using.safely.managed.drinking.water.services....of.population.                           0.0649048\n                                                                                                t-value\nPeople.practicing.open.defecation....of.population.                                             -6.6419\nPeople.using.at.least.basic.drinking.water.services....of.population.                          -10.2724\nPeople.using.at.least.basic.sanitation.services....of.population.                               -3.7624\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   4.4550\nPeople.using.safely.managed.drinking.water.services....of.population.                            2.9002\n                                                                                                Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                            9.323e-10\nPeople.using.at.least.basic.drinking.water.services....of.population.                          < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                              0.0002609\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources 1.884e-05\nPeople.using.safely.managed.drinking.water.services....of.population.                          0.0044301\n                                                                                                  \nPeople.practicing.open.defecation....of.population.                                            ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                          ***\nPeople.using.at.least.basic.sanitation.services....of.population.                              ***\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources ***\nPeople.using.safely.managed.drinking.water.services....of.population.                          ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    146.4\nResidual Sum of Squares: 22.626\nR-Squared:      0.84545\nAdj. R-Squared: 0.83267\nF-statistic: 132.38 on 5 and 121 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk provide the summary of the R-squared, Adjusted R-squared, F-statistic for both models.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_full)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      rsq    adjrsq \n0.8512139 0.8375751 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_reduced)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      rsq    adjrsq \n0.8454464 0.8326734 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_full)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_reduced)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_full)$fstatistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for joint significance\n\ndata:  DiarrheaRate ~ People.practicing.open.defecation....of.population. +  ...\nF = 114.42, df1 = 6, df2 = 120, p-value < 2.2e-16\nalternative hypothesis: at least one coefficient is not null\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(model_reduced)$fstatistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test for joint significance\n\ndata:  DiarrheaRate ~ People.practicing.open.defecation....of.population. +  ...\nF = 132.38, df1 = 5, df2 = 121, p-value < 2.2e-16\nalternative hypothesis: at least one coefficient is not null\n```\n\n\n:::\n:::\n\n\n\nThe R-Squared value of the reduced model is slightly lower than the full model, which means the full model explains a little more of the variance in DiarrheaRate.\n\nThe Adjusted R-Squared also shows a slight drop in the reduced model, though the difference is not large, indicating that removing some predictors did not dramatically reduce the model's explanatory power after adjusting for the number of predictors.\n\nBoth models show that at least one of the predictors is statistically significant (given the very low p-values).\n\nThe reduced model has a slightly higher F-statistic, which suggests that removing one predictor did not negatively affect the overall model’s significance, and may even have improved it slightly.\\\n\\\nThe full model explains slightly more variance in DiarrheaRate than the reduced model based on both R-Squared and Adjusted R-Squared.\n\nIt was decide we will be continue with our full model.\n\n### 4.3.5 PLM continue with full model\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R analyse the relationship between DiarrheaRate and WASH indicators.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(DiarrheaRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = DiarrheaRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.021289 -0.248422 -0.060002  0.257269  0.961836 \n\nCoefficients:\n                                                                                                   Estimate\nPeople.practicing.open.defecation....of.population.                                              -0.6755407\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -1.0144098\nPeople.using.at.least.basic.sanitation.services....of.population.                                -0.1706479\nPopulation.density..people.per.sq..km.of.land.area.                                               0.0014148\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0029523\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0110199\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.2855646\nPeople.using.safely.managed.sanitation.services....of.population.                                -0.1302516\n                                                                                                 Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.1085486\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.1014805\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.0915876\nPopulation.density..people.per.sq..km.of.land.area.                                               0.0052560\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.0011407\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.0034595\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.1001031\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.1234424\n                                                                                                 t-value\nPeople.practicing.open.defecation....of.population.                                              -6.2234\nPeople.using.at.least.basic.drinking.water.services....of.population.                            -9.9961\nPeople.using.at.least.basic.sanitation.services....of.population.                                -1.8632\nPopulation.density..people.per.sq..km.of.land.area.                                               0.2692\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  2.5882\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    3.1854\nPeople.using.safely.managed.drinking.water.services....of.population.                             2.8527\nPeople.using.safely.managed.sanitation.services....of.population.                                -1.0552\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              7.677e-09\nPeople.using.at.least.basic.drinking.water.services....of.population.                            < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.064917\nPopulation.density..people.per.sq..km.of.land.area.                                               0.788259\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.010860\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.001849\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.005120\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.293507\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                .  \nPopulation.density..people.per.sq..km.of.land.area.                                                 \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. *  \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ** \nPeople.using.safely.managed.drinking.water.services....of.population.                            ** \nPeople.using.safely.managed.sanitation.services....of.population.                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    146.4\nResidual Sum of Squares: 21.365\nR-Squared:      0.85406\nAdj. R-Squared: 0.83798\nF-statistic: 86.3196 on 8 and 118 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R analyse the relationship between `HeptatitisRate` and WASH indicators.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(HepatitisRate ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = HepatitisRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n      Min.    1st Qu.     Median    3rd Qu.       Max. \n-0.0677318 -0.0066636  0.0013683  0.0085389  0.0338086 \n\nCoefficients:\n                                                                                                    Estimate\nPeople.practicing.open.defecation....of.population.                                               8.5691e-03\nPeople.using.at.least.basic.drinking.water.services....of.population.                             2.3667e-02\nPeople.using.at.least.basic.sanitation.services....of.population.                                -1.1585e-02\nPopulation.density..people.per.sq..km.of.land.area.                                              -3.7942e-04\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  8.6247e-05\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -1.0463e-03\nPeople.using.safely.managed.drinking.water.services....of.population.                            -3.6054e-03\nPeople.using.safely.managed.sanitation.services....of.population.                                -5.7112e-04\n                                                                                                  Std. Error\nPeople.practicing.open.defecation....of.population.                                               3.8073e-03\nPeople.using.at.least.basic.drinking.water.services....of.population.                             3.5594e-03\nPeople.using.at.least.basic.sanitation.services....of.population.                                 3.2124e-03\nPopulation.density..people.per.sq..km.of.land.area.                                               1.8435e-04\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  4.0009e-05\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    1.2134e-04\nPeople.using.safely.managed.drinking.water.services....of.population.                             3.5111e-03\nPeople.using.safely.managed.sanitation.services....of.population.                                 4.3297e-03\n                                                                                                 t-value\nPeople.practicing.open.defecation....of.population.                                               2.2507\nPeople.using.at.least.basic.drinking.water.services....of.population.                             6.6490\nPeople.using.at.least.basic.sanitation.services....of.population.                                -3.6063\nPopulation.density..people.per.sq..km.of.land.area.                                              -2.0581\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  2.1557\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -8.6230\nPeople.using.safely.managed.drinking.water.services....of.population.                            -1.0269\nPeople.using.safely.managed.sanitation.services....of.population.                                -0.1319\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              0.0262575\nPeople.using.at.least.basic.drinking.water.services....of.population.                            9.653e-10\nPeople.using.at.least.basic.sanitation.services....of.population.                                0.0004564\nPopulation.density..people.per.sq..km.of.land.area.                                              0.0417807\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. 0.0331398\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   3.505e-14\nPeople.using.safely.managed.drinking.water.services....of.population.                            0.3065854\nPeople.using.safely.managed.sanitation.services....of.population.                                0.8952825\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              *  \nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                ***\nPopulation.density..people.per.sq..km.of.land.area.                                              *  \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. *  \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ***\nPeople.using.safely.managed.drinking.water.services....of.population.                               \nPeople.using.safely.managed.sanitation.services....of.population.                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    0.475\nResidual Sum of Squares: 0.026284\nR-Squared:      0.94467\nAdj. R-Squared: 0.93857\nF-statistic: 251.814 on 8 and 118 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R analyse the relationship between `unsafetyRisk` and WASH indicators.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(UnsafeRisk ~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = UnsafeRisk ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-1.683001 -0.073009  0.020810  0.128213  0.580755 \n\nCoefficients:\n                                                                                                    Estimate\nPeople.practicing.open.defecation....of.population.                                               0.72708968\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.43477443\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.21651056\nPopulation.density..people.per.sq..km.of.land.area.                                               0.00037018\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.00063762\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -0.01913748\nPeople.using.safely.managed.drinking.water.services....of.population.                            -0.25010937\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.04852111\n                                                                                                  Std. Error\nPeople.practicing.open.defecation....of.population.                                               0.07488698\nPeople.using.at.least.basic.drinking.water.services....of.population.                             0.07001070\nPeople.using.at.least.basic.sanitation.services....of.population.                                 0.06318565\nPopulation.density..people.per.sq..km.of.land.area.                                               0.00362608\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.00078695\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    0.00238667\nPeople.using.safely.managed.drinking.water.services....of.population.                             0.06906044\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.08516212\n                                                                                                 t-value\nPeople.practicing.open.defecation....of.population.                                               9.7092\nPeople.using.at.least.basic.drinking.water.services....of.population.                             6.2101\nPeople.using.at.least.basic.sanitation.services....of.population.                                 3.4266\nPopulation.density..people.per.sq..km.of.land.area.                                               0.1021\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  0.8102\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -8.0185\nPeople.using.safely.managed.drinking.water.services....of.population.                            -3.6216\nPeople.using.safely.managed.sanitation.services....of.population.                                 0.5697\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              < 2.2e-16\nPeople.using.at.least.basic.drinking.water.services....of.population.                            8.182e-09\nPeople.using.at.least.basic.sanitation.services....of.population.                                0.0008420\nPopulation.density..people.per.sq..km.of.land.area.                                              0.9188591\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. 0.4194354\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   8.713e-13\nPeople.using.safely.managed.drinking.water.services....of.population.                            0.0004328\nPeople.using.safely.managed.sanitation.services....of.population.                                0.5699304\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                ***\nPopulation.density..people.per.sq..km.of.land.area.                                                 \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.    \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ***\nPeople.using.safely.managed.drinking.water.services....of.population.                            ***\nPeople.using.safely.managed.sanitation.services....of.population.                                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    157.97\nResidual Sum of Squares: 10.169\nR-Squared:      0.93563\nAdj. R-Squared: 0.92854\nF-statistic: 214.394 on 8 and 118 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk fits a Fixed Effects Model also known as the 'within' model) using the `plm` function from the `plm` package in R analyse the relationship between `TyphoidRate` and WASH indicators.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- plm(TyphoidRate~ \n  People.practicing.open.defecation....of.population. +\n  People.using.at.least.basic.drinking.water.services....of.population. +\n  People.using.at.least.basic.sanitation.services....of.population. +\n  Population.density..people.per.sq..km.of.land.area. +\n  Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. +\n  Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources +  # Level of water stress\n  People.using.safely.managed.drinking.water.services....of.population. +  # People using safely managed drinking water services\n  People.using.safely.managed.sanitation.services....of.population.,  # People using safely managed sanitation services\n  data = pdata,\n  model = \"within\"\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOneway (individual) effect Within Model\n\nCall:\nplm(formula = TyphoidRate ~ People.practicing.open.defecation....of.population. + \n    People.using.at.least.basic.drinking.water.services....of.population. + \n    People.using.at.least.basic.sanitation.services....of.population. + \n    Population.density..people.per.sq..km.of.land.area. + Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. + \n    Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources + \n    People.using.safely.managed.drinking.water.services....of.population. + \n    People.using.safely.managed.sanitation.services....of.population., \n    data = pdata, model = \"within\")\n\nBalanced Panel: n = 6, T = 22, N = 132\n\nResiduals:\n       Min.     1st Qu.      Median     3rd Qu.        Max. \n-1.3345e-02 -1.7639e-03  3.2779e-05  1.9438e-03  6.7478e-03 \n\nCoefficients:\n                                                                                                    Estimate\nPeople.practicing.open.defecation....of.population.                                               1.5961e-02\nPeople.using.at.least.basic.drinking.water.services....of.population.                             1.8088e-02\nPeople.using.at.least.basic.sanitation.services....of.population.                                 2.4683e-03\nPopulation.density..people.per.sq..km.of.land.area.                                               9.1629e-05\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  1.1884e-05\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -4.1832e-04\nPeople.using.safely.managed.drinking.water.services....of.population.                            -4.9622e-03\nPeople.using.safely.managed.sanitation.services....of.population.                                -2.0081e-03\n                                                                                                  Std. Error\nPeople.practicing.open.defecation....of.population.                                               8.4282e-04\nPeople.using.at.least.basic.drinking.water.services....of.population.                             7.8794e-04\nPeople.using.at.least.basic.sanitation.services....of.population.                                 7.1113e-04\nPopulation.density..people.per.sq..km.of.land.area.                                               4.0810e-05\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.  8.8568e-06\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources    2.6861e-05\nPeople.using.safely.managed.drinking.water.services....of.population.                             7.7724e-04\nPeople.using.safely.managed.sanitation.services....of.population.                                 9.5846e-04\n                                                                                                  t-value\nPeople.practicing.open.defecation....of.population.                                               18.9370\nPeople.using.at.least.basic.drinking.water.services....of.population.                             22.9557\nPeople.using.at.least.basic.sanitation.services....of.population.                                  3.4710\nPopulation.density..people.per.sq..km.of.land.area.                                                2.2452\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.   1.3418\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   -15.5736\nPeople.using.safely.managed.drinking.water.services....of.population.                             -6.3844\nPeople.using.safely.managed.sanitation.services....of.population.                                 -2.0952\n                                                                                                  Pr(>|t|)\nPeople.practicing.open.defecation....of.population.                                              < 2.2e-16\nPeople.using.at.least.basic.drinking.water.services....of.population.                            < 2.2e-16\nPeople.using.at.least.basic.sanitation.services....of.population.                                0.0007252\nPopulation.density..people.per.sq..km.of.land.area.                                              0.0266147\nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. 0.1822283\nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   < 2.2e-16\nPeople.using.safely.managed.drinking.water.services....of.population.                             3.53e-09\nPeople.using.safely.managed.sanitation.services....of.population.                                0.0382947\n                                                                                                    \nPeople.practicing.open.defecation....of.population.                                              ***\nPeople.using.at.least.basic.drinking.water.services....of.population.                            ***\nPeople.using.at.least.basic.sanitation.services....of.population.                                ***\nPopulation.density..people.per.sq..km.of.land.area.                                              *  \nWater.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.    \nLevel.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources   ***\nPeople.using.safely.managed.drinking.water.services....of.population.                            ***\nPeople.using.safely.managed.sanitation.services....of.population.                                *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    0.062059\nResidual Sum of Squares: 0.001288\nR-Squared:      0.97925\nAdj. R-Squared: 0.97696\nF-statistic: 695.932 on 8 and 118 DF, p-value: < 2.22e-16\n```\n\n\n:::\n:::\n\n\n\nBase on the output of four model, People practicing open defecation and People using at least basic drinking water services are significant across all models, consistently showing a negative relationship with health outcomes. `Level of water stress` appears as significant in most models, suggesting that regions facing higher water stress tend to experience worse health outcomes. `People using safely managed drinking water services` has significant positive impacts on `DiarrheaRate` and `UnsafeRisk`, but it is not significant for `HepatitisRate`.\n\nThe models explaining `HepatitisRate` and `UnsafeRisk` have very high R-squared values (above 94%), suggesting that these models explain most of the variance in the respective dependent variables.The `DiarrheaRate` model has a slightly lower R-squared (85.4%), but still a very good fit.\n\nThe results show that sanitation, drinking water access, and open defecation are important factors influencing health outcomes, particularly `DiarrheaRate` and `UnsafeRisk`.Water stress plays a critical role, indicating that regions with high water stress are likely to face more health-related challenges.There is considerable variation in the impact of predictors on different health outcomes, with some predictors (e.g., `People using safely managed drinking water services`) being more influential for some health outcomes than others.\n\n## 4.4 Coefficient list\n\nThe code chunk below create a list of coefficient for four different health outcome, `DiarrheaRate`, `TyphoidRate`, `UnsafeRisk`, and `HepatitisRate` from the fixed effects models.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_list <- list(\n  DiarrheaRate = c(\n    OpenDefecation = -0.6755407,\n    BasicWater = -1.0144098,\n    BasicSanitation = -0.1706479,\n    WaterProductivity = 0.0029523,\n    WaterStress = 0.0110199,\n    PopulationDensity = 0.0014148,\n    SafelyManagedWater = 0.2855646,\n    SafelyManagedSanitation = -0.1302516\n  ),\n  TyphoidRate = c(\n    OpenDefecation = 0.015961,\n    BasicWater = 0.018088,\n    BasicSanitation = 0.0024683,\n    WaterProductivity = 1.1884e-05,\n    WaterStress = -4.1832e-04,\n    PopulationDensity = 9.1629e-05,\n    SafelyManagedWater = -4.9622e-03,\n    SafelyManagedSanitation = -2.0081e-03\n  ),\n  UnsafeRisk = c(\n    OpenDefecation = 0.72708968,\n    BasicWater = 0.43477443,\n    BasicSanitation = 0.21651056,\n    WaterProductivity = 0.00063762,\n    WaterStress = -0.01913748,\n    PopulationDensity = 0.00037018,\n    SafelyManagedWater = -0.25010937,\n    SafelyManagedSanitation = 0.04852111\n  ),\n  HepatitisRate = c(\n    OpenDefecation = 0.0085691,\n    BasicWater = 0.023667,\n    BasicSanitation = -0.011585,\n    WaterProductivity = 8.6247e-05,\n    WaterStress = -0.0010463,\n    PopulationDensity = -3.7942e-04,\n    SafelyManagedWater = -3.6054e-03,\n    SafelyManagedSanitation = -5.7112e-04\n  )\n)\n```\n:::\n\n\n\n# 5. Time Series Analysis for period 2022 to 2030 for wash indicators\n\n## 5.1 Create `selected_data`\n\nThe below code chunk use `dplyr` package to select all the variables that will be use for analysis in the `pdata`. This is done using the `select()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_data <- pdata %>%\n  select(Region, Year, TyphoidRate, DiarrheaRate, HepatitisRate, \n         UnsafeRisk, \n         \"Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources\",\n         \"People.practicing.open.defecation....of.population.\",\n         \"People.using.at.least.basic.drinking.water.services....of.population.\",\n         \"People.using.at.least.basic.sanitation.services....of.population.\",\n         \"People.using.safely.managed.drinking.water.services....of.population.\",\n         \"People.using.safely.managed.sanitation.services....of.population.\",\n         \"Population.density..people.per.sq..km.of.land.area.\",\n         \"Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.\")\n```\n:::\n\n\n\nThe `view(selected_data)` function in R will open a spreadsheet-like view of the `selected_data` data frame in RStudio, allowing interactively explore and inspect the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nview(selected_data)\n```\n:::\n\n\n\n### 5.2 Converting Data type\n\nThe function `class()` and `typeof()` provide different types of information about the Year column in the `selected_data.`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(selected_data$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"pseries\" \"factor\" \n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(selected_data$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n\n\nThe below code chunk ensure that if the `Year` column in the `selected_data` is a factor it will be converted into a numeric format.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_data$Year <- as.numeric(as.character(selected_data$Year))\n```\n:::\n\n\n\nThe below code chunk use function `extract_year()` that extracts a 4-digit year from a mixed string and then cleans the `Year` column in your `selected_data` dataset by applying this function. Finally, it converts the `Year` to a Date format representing the first day of the year.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_year <- function(x) {\n  year <- str_extract(x, \"\\\\d{4}\")\n  return(as.numeric(year))\n}\n\nselected_data$Year <- extract_year(selected_data$Year)\n\nselected_data$YearDate <- as.Date(paste0(selected_data$Year, \"-01-01\"))\n```\n:::\n\n\n\nThe below code chunk using str() function provides a compact display the structure of the an object, including its type and other relevant details. The `str(selected_data$Year)`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the type of the 'Year' column\nstr(selected_data$Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 'pseries' Named num [1:132] 2000 2001 2002 2003 2004 ...\n - attr(*, \"names\")= chr [1:132] \"African Region-2000\" \"African Region-2001\" \"African Region-2002\" \"African Region-2003\" ...\n - attr(*, \"index\")=Classes 'pindex' and 'data.frame':\t132 obs. of  2 variables:\n  ..$ Region: Factor w/ 6 levels \"African Region\",..: 1 1 1 1 1 1 1 1 1 1 ...\n  ..$ Year  : Factor w/ 22 levels \"2000\",\"2001\",..: 1 2 3 4 5 6 7 8 9 10 ...\n```\n\n\n:::\n:::\n\n\n\n### 5.3 Times Series Analysis using ARIMA\n\nThe below code chunk perform ARIMA (Auto-Regression Integrated Moving Average) time series forecasting for WHO regions based on historical data. It generate the WASH indicators and population from 2022 to 2030.\\\nThe code chunk processes data region-by-region, checks the availability of necessary data, fits ARIMA models, and returns the forecasted values for the next several years, which can be used for policy planning, resource allocation, or trend analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narima_forecast <- function(data, forecast_start_year = 2022, forecast_end_year = 2030) {\n\n#define variable name \n  forecast_vars <- c(\n    \"WaterStress\" = \"Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources\",\n    \"OpenDefecation\" = \"People.practicing.open.defecation....of.population.\",\n    \"BasicWaterServices\" = \"People.using.at.least.basic.drinking.water.services....of.population.\",\n    \"BasicSanitationServices\" = \"People.using.at.least.basic.sanitation.services....of.population.\",\n    \"SafeManagedWaterServices\" = \"People.using.safely.managed.drinking.water.services....of.population.\",\n    \"SafeManagedSanitationServices\" = \"People.using.safely.managed.sanitation.services....of.population.\",\n    \"PopulationDensity\" = \"Population.density..people.per.sq..km.of.land.area.\",\n    \"WaterProductivity\" = \"Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.\"\n  )\n  \n  # Print progress header\n  cat(\"========================================\\n\")\n  cat(\"Starting ARIMA forecasting for\", forecast_start_year, \"to\", forecast_end_year, \"\\n\")\n  cat(\"========================================\\n\\n\")\n  \n  # Verify input data\n  cat(\"Verifying input data...\\n\")\n  cat(\"Input data has\", nrow(data), \"rows and\", ncol(data), \"columns\\n\")\n  \n  # Check if required columns exist\n  required_cols <- c(\"Region\", \"Year\")\n  missing_required <- setdiff(required_cols, names(data))\n  if (length(missing_required) > 0) {\n    stop(\"Missing required columns: \", paste(missing_required, collapse = \", \"))\n  }\n  \n  # Check for variable columns\n  available_vars <- intersect(forecast_vars, names(data))\n  if (length(available_vars) == 0) {\n    stop(\"None of the forecast variables found in the data\")\n  }\n  cat(\"Found\", length(available_vars), \"out of\", length(forecast_vars), \"forecast variables\\n\")\n  \n  # Get unique regions\n  regions <- unique(data$Region)\n  cat(\"Found\", length(regions), \"regions:\", paste(regions, collapse = \", \"), \"\\n\\n\")\n  \n  # Create empty data frame for results\n  all_forecasts <- data.frame()\n  \n  # Process each region\n  for (region in regions) {\n    cat(\"Processing region:\", region, \"\\n\")\n    \n    # Filter data for this region\n    region_data <- data %>% filter(Region == region)\n    cat(\"  Region has\", nrow(region_data), \"rows\\n\")\n    \n    # Create an empty data frame for this region's forecasts\n    region_forecasts <- expand.grid(\n      Region = region,\n      Year = forecast_start_year:forecast_end_year,\n      stringsAsFactors = FALSE\n    )\n    # Add DataType column\n    region_forecasts$DataType <- \"Forecast\"\n    \n    # Process each variable\n    for (short_name in names(forecast_vars)) {\n      var_name <- forecast_vars[short_name]\n      cat(\"  Forecasting:\", short_name, \"(\", var_name, \")\\n\")\n      \n      # Check if variable exists in data\n      if (!(var_name %in% names(region_data))) {\n        cat(\"    Variable not found in data, skipping\\n\")\n        region_forecasts[[short_name]] <- NA\n        next\n      }\n      \n      # Get historical data for this variable\n      var_data <- region_data %>% \n        filter(!is.na(!!sym(var_name)), Year < forecast_start_year) %>%\n        arrange(Year)\n      \n      # Check if enough data\n      if (nrow(var_data) < 5) {\n        cat(\"    Insufficient historical data (need at least 5 points), skipping\\n\")\n        region_forecasts[[short_name]] <- NA\n        next\n      }\n      \n      # Create time series\n      cat(\"    Creating time series with\", nrow(var_data), \"points from\", \n          min(var_data$Year), \"to\", max(var_data$Year), \"\\n\")\n      \n      ts_data <- ts(var_data[[var_name]], \n                   start = min(var_data$Year), \n                   end = max(var_data$Year), \n                   frequency = 1)\n      \n      # Fit ARIMA model and forecast\n      tryCatch({\n        cat(\"    Fitting ARIMA model...\\n\")\n        arima_model <- auto.arima(ts_data, seasonal = FALSE, stepwise = TRUE)\n        \n        # Print model information\n        cat(\"    Model:\", arimaorder(arima_model), \"\\n\")\n        \n        # Generate forecast\n        forecast_years <- forecast_end_year - forecast_start_year + 1\n        cat(\"    Generating\", forecast_years, \"year forecast...\\n\")\n        forecast_result <- forecast(arima_model, h = forecast_years)\n        \n        # Add forecast to results\n        region_forecasts[[short_name]] <- as.numeric(forecast_result$mean)\n        \n        # Print forecast summary\n        cat(\"    Forecast summary - First:\", round(forecast_result$mean[1], 4),\n            \"Last:\", round(forecast_result$mean[forecast_years], 4), \"\\n\")\n        \n      }, error = function(e) {\n        cat(\"    Error in forecasting:\", e$message, \"\\n\")\n        region_forecasts[[short_name]] <- NA\n      })\n    }\n    \n    # Add this region's forecasts to the overall results\n    all_forecasts <- bind_rows(all_forecasts, region_forecasts)\n    cat(\"  Completed forecasts for\", region, \"\\n\\n\")\n  }\n  \n  # Print summary\n  cat(\"========================================\\n\")\n  cat(\"ARIMA forecasting complete\\n\")\n  cat(\"Generated forecasts for\", nrow(all_forecasts), \"rows\\n\")\n  cat(\"Forecasted variables:\", paste(names(all_forecasts)[!(names(all_forecasts) %in% c(\"Region\", \"Year\", \"DataType\"))], collapse = \", \"), \"\\n\")\n  cat(\"========================================\\n\\n\")\n  \n  # Return the clean format results with short names\n  return(all_forecasts)\n}\n```\n:::\n\n\n\nThe below code chunk run the `arima_forecast` from above code chunk, generating forecasts for year 2022 to 2030. The resulting forecasted data is then saved to a csv file name `water_sanitation_forecasts.csv` .\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n forecast_data <-arima_forecast(selected_data, \n                                         forecast_start_year = 2022, \n                                          forecast_end_year = 2030)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n========================================\nStarting ARIMA forecasting for 2022 to 2030 \n========================================\n\nVerifying input data...\nInput data has 132 rows and 15 columns\nFound 8 out of 8 forecast variables\nFound 6 regions: African Region, Eastern Mediterranean Region, European Region, Region of the Americas, South-East Asia Region, Western Pacific Region \n\nProcessing region: African Region \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 13.6691 Last: 15.0825 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 16.6458 Last: 12.6728 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 71.0816 Last: 76.0508 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 41.3846 Last: 46.1911 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 26.6579 Last: 29.7478 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 23.602 Last: 26.1116 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 123.6346 Last: 142.6114 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 50.8416 Last: 51.5612 \n  Completed forecasts for African Region \n\nProcessing region: Eastern Mediterranean Region \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 434.4198 Last: 477.9403 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 3.4662 Last: 0.4362 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 90.1361 Last: 93.579 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 87.4697 Last: 89.1055 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 3 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 75.6946 Last: 76.178 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 63.9669 Last: 61.6175 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 246.9798 Last: 287.6959 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 75.2812 Last: 90.2432 \n  Completed forecasts for Eastern Mediterranean Region \n\nProcessing region: European Region \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 29.106 Last: 27.9702 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 0.0173 Last: 0.0163 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 98.219 Last: 98.4982 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 97.367 Last: 97.6688 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 91.6315 Last: 91.4817 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 3 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 81.1007 Last: 84.2264 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 510.6295 Last: 487.6131 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 166.4738 Last: 197.3617 \n  Completed forecasts for European Region \n\nProcessing region: Region of the Americas \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 14.7549 Last: 15.361 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 2.0797 Last: 1.1645 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 96.0721 Last: 97.3119 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 88.8033 Last: 93.0552 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 2 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 70.6284 Last: 73.344 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 2 \n    Generating 9 year forecast...\n    Forecast summary - First: 50.1699 Last: 53.2325 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 136.9497 Last: 140.3939 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 39.9161 Last: 39.9161 \n  Completed forecasts for Region of the Americas \n\nProcessing region: South-East Asia Region \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 34.9278 Last: 34.9278 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 2.9154 Last: -2.8741 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 94.3236 Last: 97.5214 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 84.3762 Last: 96.7598 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 50.2925 Last: 53.7727 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 45.787 Last: 54.3177 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 437.9126 Last: 490.0413 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 0 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 143.4833 Last: 143.4833 \n  Completed forecasts for South-East Asia Region \n\nProcessing region: Western Pacific Region \n  Region has 22 rows\n  Forecasting: WaterStress ( Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 24.028 Last: 24.3192 \n  Forecasting: OpenDefecation ( People.practicing.open.defecation....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 6.4089 Last: 4.2022 \n  Forecasting: BasicWaterServices ( People.using.at.least.basic.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 90.9617 Last: 93.5111 \n  Forecasting: BasicSanitationServices ( People.using.at.least.basic.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 81.5416 Last: 85.5992 \n  Forecasting: SafeManagedWaterServices ( People.using.safely.managed.drinking.water.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 55.5271 Last: 58.4247 \n  Forecasting: SafeManagedSanitationServices ( People.using.safely.managed.sanitation.services....of.population. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 1 2 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 65.9229 Last: 66.8086 \n  Forecasting: PopulationDensity ( Population.density..people.per.sq..km.of.land.area. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 1 \n    Generating 9 year forecast...\n    Forecast summary - First: 453.8227 Last: 481.3429 \n  Forecasting: WaterProductivity ( Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal. )\n    Creating time series with 22 points from 2000 to 2021 \n    Fitting ARIMA model...\n    Model: 0 1 0 \n    Generating 9 year forecast...\n    Forecast summary - First: 118.3247 Last: 146.8719 \n  Completed forecasts for Western Pacific Region \n\n========================================\nARIMA forecasting complete\nGenerated forecasts for 54 rows\nForecasted variables: WaterStress, OpenDefecation, BasicWaterServices, BasicSanitationServices, SafeManagedWaterServices, SafeManagedSanitationServices, PopulationDensity, WaterProductivity \n========================================\n```\n\n\n:::\n\n```{.r .cell-code}\n write.csv(forecast_data, \"water_sanitation_forecasts.csv\", row.names = FALSE)\n```\n:::\n\n\n\nThe `view(forecast_data)` command will open a viewer in RStudio, displaying the `forecast_data` dataset in a spreadsheet-like format.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nview(forecast_data)\n```\n:::\n\n\n\n# 6. Forecast for health indicator\n\n## 6.1 Apply coefficient to forecast data\n\nThe below code chunk generates predictions for disease rates (Diarrhea, Typhoid, Unsafe Risk, and Hepatitis) based on forecasted changes in key water and sanitation variables (e.g., open defecation, basic water services, population density) for each region. The function first retrieves baseline values from the historical data for 2021, then calculates the forecasted disease rates for each region between 2022 and 2030 by applying coefficients that quantify the impact of changes in the variables. It iterates over each region and variable, adjusting the baseline values according to the forecasted changes, and ensures that negative disease values are set to zero. The function returns the updated dataset with forecasted disease rates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict_diseases <- function(forecast_data, selected_data) {\n  var_mapping <- c(\n    \"Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources\" = \"WaterStress\",\n    \"People.practicing.open.defecation....of.population.\" = \"OpenDefecation\",\n    \"People.using.at.least.basic.drinking.water.services....of.population.\" = \"BasicWaterServices\",\n    \"People.using.at.least.basic.sanitation.services....of.population.\" = \"BasicSanitationServices\",\n    \"People.using.safely.managed.drinking.water.services....of.population.\" = \"SafeManagedWaterServices\",\n    \"People.using.safely.managed.sanitation.services....of.population.\" = \"SafeManagedSanitationServices\",\n    \"Population.density..people.per.sq..km.of.land.area.\" = \"PopulationDensity\",\n    \"Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.\" = \"WaterProductivity\"\n  )\n  \n\n  historical <- as.data.frame(selected_data)\n  \n\n  baseline <- historical[historical$Year == 2021, ]\n  \n\n  coef_list <- list(\n    DiarrheaRate = c(\n      OpenDefecation = -0.6755407,\n      BasicWaterServices = -1.0144098,\n      BasicSanitationServices = -0.1706479,\n      WaterProductivity = 0.0029523,\n      WaterStress = 0.0110199,\n      PopulationDensity = 0.0014148,\n      SafeManagedWaterServices = 0.2855646,\n      SafeManagedSanitationServices = -0.1302516\n    ),\n    TyphoidRate = c(\n      OpenDefecation = 0.015961,\n      BasicWaterServices = 0.018088,\n      BasicSanitationServices = 0.0024683,\n      WaterProductivity = 1.1884e-05,\n      WaterStress = -4.1832e-04,\n      PopulationDensity = 9.1629e-05,\n      SafeManagedWaterServices = -4.9622e-03,\n      SafeManagedSanitationServices = -2.0081e-03\n    ),\n    UnsafeRisk = c(\n      OpenDefecation = 0.72708968,\n      BasicWaterServices = 0.43477443,\n      BasicSanitationServices = 0.21651056,\n      WaterProductivity = 0.00063762,\n      WaterStress = -0.01913748,\n      PopulationDensity = 0.00037018,\n      SafeManagedWaterServices = -0.25010937,\n      SafeManagedSanitationServices = 0.04852111\n    ),\n    HepatitisRate = c(\n      OpenDefecation = 0.0085691,\n      BasicWaterServices = 0.023667,\n      BasicSanitationServices = -0.011585,\n      WaterProductivity = 8.6247e-05,\n      WaterStress = -0.0010463,\n      PopulationDensity = -3.7942e-04,\n      SafeManagedWaterServices = -3.6054e-03,\n      SafeManagedSanitationServices = -5.7112e-04\n    )\n  )\n  \n  \n  result <- forecast_data\n  \n \n  for (disease in names(coef_list)) {\n    result[[disease]] <- NA\n  }\n  \n\n  for (region in unique(result$Region)) {\n\n    region_baseline <- baseline[baseline$Region == region, ]\n    \n    if (nrow(region_baseline) == 0) {\n      next\n    }\n    \n \n    region_rows <- which(result$Region == region)\n    \n   \n    for (disease in names(coef_list)) {\n   \n      baseline_value <- region_baseline[[disease]]\n      \n      for (row in region_rows) {\n      \n        result[row, disease] <- baseline_value\n        \n        for (pred_name in names(coef_list[[disease]])) {\n          \n          forecast_col <- pred_name\n          \n          historical_col <- names(var_mapping)[var_mapping == forecast_col]\n          \n          if (length(historical_col) == 0 || !forecast_col %in% names(result)) {\n            next\n          }\n          \n          baseline_val <- region_baseline[[historical_col]]\n          forecast_val <- result[row, forecast_col]\n          \n          if (is.na(baseline_val) || is.na(forecast_val)) {\n            next\n          }\n          \n          coef_val <- coef_list[[disease]][pred_name]\n          change <- forecast_val - baseline_val\n          effect <- coef_val * change\n          result[row, disease] <- result[row, disease] + effect\n        }\n      }\n    }\n  }\n  \n  # Set all negative disease values to zero\n  for (disease in names(coef_list)) {\n    negative_rows <- which(result[[disease]] < 0)\n    if (length(negative_rows) > 0) {\n      result[negative_rows, disease] <- 0\n    }\n  }\n  \n  return(result)\n}\n```\n:::\n\n\n\nThe code chunk below runs the `predict_diseases` created above, generating the predicted disease rates for each region and year. It then saves the results to a csv file named `disease_predictions.csv`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_forecasts <- predict_diseases(forecast_data, selected_data)\n\n\nwrite.csv(disease_forecasts, \"disease_predictions.csv\", row.names = FALSE)\n```\n:::\n\n\n\nThe `view(disease_forecasts)` function will open a spreadsheet-like viewer in RStudio, displaying the contents of the **`disease_forecasts`** data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nview(disease_forecasts)\n```\n:::\n\n\n\n# 7.Merging Historical data with Forcasted data\n\nThe code combines historical and forecasted data by first mapping the original water and sanitation variables from the `selected_data` dataset to standardized names, then cleaning and adding relevant columns for disease rates (e.g., DiarrheaRate, TyphoidRate) and water-related variables (e.g., WaterStress, PopulationDensity). It adds a `DataType` column to distinguish historical from forecast data, merges both datasets, and sorts them by Region and Year. Finally, the combined data is saved as a CSV file, `combined_complete_data.csv`, containing both historical and forecasted values for further analysis or reporting.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistorical_vars <- c(\n  \"Level.of.water.stress..freshwater.withdrawal.as.a.proportion.of.available.freshwater.resources\",\n  \"People.practicing.open.defecation....of.population.\",\n  \"People.using.at.least.basic.drinking.water.services....of.population.\",\n  \"People.using.at.least.basic.sanitation.services....of.population.\",\n  \"People.using.safely.managed.drinking.water.services....of.population.\",\n  \"People.using.safely.managed.sanitation.services....of.population.\",\n  \"Population.density..people.per.sq..km.of.land.area.\",\n  \"Water.productivity..total..constant.2015.US..GDP.per.cubic.meter.of.total.freshwater.withdrawal.\"\n)\n\nforecast_vars <- c(\n  \"WaterStress\",\n  \"OpenDefecation\",\n  \"BasicWaterServices\",\n  \"BasicSanitationServices\",\n  \"SafeManagedWaterServices\", \n  \"SafeManagedSanitationServices\",\n  \"PopulationDensity\",\n  \"WaterProductivity\"\n)\n\n\nvar_mapping <- setNames(forecast_vars, historical_vars)\n\n\nhistorical_data <- as.data.frame(selected_data)\n\nhistorical_data$DataType <- \"Historical\"\n\n\nhistorical_clean <- historical_data[, c(\"Region\", \"Year\", \"TyphoidRate\", \"DiarrheaRate\", \n                                       \"HepatitisRate\", \"UnsafeRisk\", \"DataType\")]\n\n\nfor (hist_var in names(var_mapping)) {\n  if (hist_var %in% names(historical_data)) {\n    forecast_var <- var_mapping[hist_var]\n    historical_clean[[forecast_var]] <- historical_data[[hist_var]]\n  }\n}\n\n\ncombined_data <- rbind(historical_clean, disease_forecasts)\n\n\ncombined_data <- combined_data[order(combined_data$Region, combined_data$Year), ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(combined_data, \"combined_complete_data.csv\", row.names = FALSE)\n```\n:::\n\n\n\n# 8. Visualize test result\n\n## 8.1 Importing the combined data\n\nThe below code chunk use `read.csv()` to read the `combined_complete_data.csv`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data <- read.csv(\"combined_complete_data.csv\")\n```\n:::\n\n\n\n## 8.2 plotting for visualization\n\nThe below code chunk creates a line plot using `ggplot2` to visualise the historical result and forecast result of the `DiarrheaRate`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(combined_data, aes(x = Year, y = DiarrheaRate, color = Region, linetype = DataType)) +\n  geom_line() +\n  geom_point() +\n  labs(title = \"Diarrhea Rate: Historical and Forecast\", y = \"Rate\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_Part1_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data_long <- combined_data %>%\n  pivot_longer(cols = c(UnsafeRisk, WaterStress, OpenDefecation, BasicWaterServices, \n                        BasicSanitationServices, SafeManagedWaterServices, \n                        SafeManagedSanitationServices, WaterProductivity),\n               names_to = \"WASH_Variable\", values_to = \"Value\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(combined_data_long, aes(x = Year, y = Value, color = Region, linetype = DataType)) +\n  geom_line() +\n  geom_point() +\n  facet_wrap(~WASH_Variable, scales = \"free_y\") +  # Facet by WASH variable\n  labs(title = \"WASH Variables Over Time by Region\", y = \"Value\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_Part1_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tidyr)\n\n# Load the combined data\ncombined_data <- read.csv(\"combined_complete_data.csv\")\n\n# Reshape the data to a longer format for both WASH and disease variables\ncombined_data_long <- combined_data %>%\n  pivot_longer(cols = c(UnsafeRisk, WaterStress, OpenDefecation, BasicWaterServices, \n                        BasicSanitationServices, SafeManagedWaterServices, \n                        SafeManagedSanitationServices, WaterProductivity,\n                        TyphoidRate, DiarrheaRate, HepatitisRate),\n               names_to = \"Variable\", values_to = \"Value\")\n\n# Plot all WASH and disease variables for all regions\nggplot(combined_data_long, aes(x = Year, y = Value, color = Region, linetype = DataType)) +\n  geom_line() +\n  geom_point() +\n  facet_wrap(~Variable, scales = \"free_y\") +  # Facet by variable (WASH + diseases)\n  labs(title = \"WASH and Disease Variables Over Time by Region\", y = \"Value\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex3_Part1_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Take-home_Ex3_Part1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}